### ISSUE TITLE
Resetting Resource Packs

### ISSUE THREAD

**Issue by Grausamste** [indi-code/Informed-Load#11]
Version 3.0.2 prevents resource packs from loading on game start, requiring them to be reactivated every time you open Minecraft.

**Comment by IdrisQe** [comment]
This is correct. I finally found out the cause, and it was this mod, same version.

**Comment by indi-code** [comment]
:/ thats probably my stupid injection point. disable the modloading status @Grausamste @IdrisQe

**Comment by Cicero-Interactive** [comment]
Any plans on releasing an update fixing this?
