### ISSUE TITLE
Crash when using Blur mod

### ISSUE THREAD

**Issue by magneticflux-** [indi-code/Informed-Load#12]
I checked the other crashes reported recently, and mine seems different.
Here's the log: https://paste.ee/p/SGABB

**Comment by indi-code** [comment]
run IL in print entrypoints mode (its in the config) and show me the output

**Comment by indi-code** [comment]
with just the two mods

**Comment by magneticflux-** [comment]
Here's the result:
```
[20:15:47] [main/INFO]: [STDOUT]: [Informed Load] Displaying mod entrypoints:
Informed Load (informedload)
|--io.github.indicode.fabric.informedload.InformedLoadUtils
Blur (blur)
|--com.tterrag.blur.Blur
Auto Config v1 (autoconfig1)
|--me.sargunvohra.mcmods.autoconfig1.example.ExampleInit
|--me.sargunvohra.mcmods.autoconfig1.example.ExampleInit
Cloth Config (cloth-config)
|--me.shedaniel.clothconfig.ClothConfigInitializer
[20:15:47] [main/INFO]: [STDOUT]: [Informed Load] Done, Shutting down Minecraft.
Process exited with code 0.
```

Adding `com.tterrag.blur.Blur` to the `excludedEntrypoints` array lets Minecraft load properly.

**Comment by indi-code** [comment]
Yep you found the fix. I'll make a pr to blur if its open source to fix that. (After adding nessecary hooks on my end)
