### ISSUE TITLE
v3.0.2 causes hotkeys from many mods to not appear in Controls Menu

### ISSUE THREAD

**Issue by IdrisQe** [indi-code/Informed-Load#13]
The title says all.
I noticed that the hotkeys from Amecs and Mouse Wheelie weren't showing in my controls.
The hotkeys from VoxelMap _were_ showing just fine, however.
This occurs with Fabric API 0.4.1-build245 and Loader 0.6.3-build168, the latest at the time of posting.

Edit: Informed Load **also** stops hotkeys from the following mods from showing in the controls menu:
-Light Overlay
-Roughly Enough Items
-Giselbaer's Durability Viewer
-Presence Footsteps
in addition to:
-Amecs
-Mouse Wheelie

The only mod that WAS showing its hotkeys with Informed Load installed was VoxelMap.

**Comment by Siphalor** [comment]
It essentially destroys the keybindings of **all** mods that use Fabric API for that. 
The only keybindings showing up are Voxel Map's ones since it most likely uses some custom approach.

**Comment by indi-code** [comment]
Also the injection point. disable fancy modloading status for now @Siphalor @IdrisQe
