### ISSUE TITLE
Crash with Fabric 1.14.4

### ISSUE THREAD

**Issue by Brittank88** [indi-code/Informed-Load#3]
Loader Version: 0.4.8 build 157-1.14.4
Fabric API Version: 0.3.0 build 200
Crash Report: https://pastebin.com/KMC5DC7k

Just thought I'd bring your attention to this in the hopes it's fixable!

Let me know if any more info is required.

**Comment by indi-code** [comment]
Working on it right now - looks like Mojang changed thier mappings.

**Comment by Brittank88** [comment]
Thanks for getting back to me!
You know, I think I did actually hear about the mapping change somewhere now that I think about it..

**Comment by indi-code** [comment]
I think I fixed this a while ago... Sorry i forgot to clase this...
