### ISSUE TITLE
"Models Baked" stops at n-1/n and never gets cleaned up

### ISSUE THREAD

**Issue by BobLemon23** [indi-code/Informed-Load#6]
The Models Baked bar never gets filled and stops at n-1/n instead. It is therefore never cleared, and new bars are created whenever the loading screen reappears (e.g. resource pack changes).

![Models Baked Bars](https://user-images.githubusercontent.com/55948721/66111101-7f17d900-e5c8-11e9-8e6c-70fb2c99efd1.png)

**Comment by indi-code** [comment]
fixed in 3.0.0
