### ISSUE TITLE
Models/Blockstates added by Artifice don't load when using Informed Load

### ISSUE THREAD

**Issue by MarioAndWeegee3** [indi-code/Informed-Load#7]
Models and blockstates added through [Artifice](https://github.com/artificemc/artifice) don't load correctly with Informed Load installed. To replicate, install Informed Load alongside a mod that uses Artifice (Such as [Extra Pieces](https://www.curseforge.com/minecraft/mc-mods/extra-pieces)). The models are not correctly loaded; the log says that the files do not exist.

**Comment by indi-code** [comment]
Fixed in 3.0.2
