### ISSUE TITLE
Crashing on 1.14.4

### ISSUE THREAD

**Issue by Onixiya** [indi-code/Informed-Load#8]
https://pastebin.com/JaK8PpPE

got it from https://www.curseforge.com/minecraft/mc-mods/informed-load/files/2807108

if you need anymore information, i'll gladly provide it

**Comment by indi-code** [comment]
Thats not mine.
Some mod is looking for this block: 
`java.lang.NoClassDefFoundError: io/github/alexiyorlov/BaseFluidBlock`
100% not informed load.

**Comment by indi-code** [comment]
Does it work without informed load though? It could be messing up the load order. Try it without and see if you get the same thing

**Comment by Onixiya** [comment]
nvm, seems to work now but when i gave it the new version it crashed
